### ISSUE TITLE
不明原因报错

### ISSUE THREAD

**Issue by ata666** [Wyatt1026/BilibiliDailyUp#23]
[INFO] 本次投币任务数量:5
Traceback (most recent call last):
  File "/ql/data/scripts/BilibiliDailyUp/main.py", line 16, in <module>
    bilibili.go()
  File "/ql/data/scripts/BilibiliDailyUp/core/bilibili.py", line 155, in go
    self.do_job()
  File "/ql/data/scripts/BilibiliDailyUp/core/bilibili.py", line 122, in do_job
    handler(job_status)
  File "/ql/data/scripts/BilibiliDailyUp/core/bilibili.py", line 97, in handle_insert_coin
    self.do_insert_coin(strict_mode=config.STRICT_MODE, coin_has_inserted_num=status)
  File "/ql/data/scripts/BilibiliDailyUp/core/bilibili.py", line 54, in do_insert_coin
    coin_res = self.insert_coins()
  File "/ql/data/scripts/BilibiliDailyUp/core/bilibili.py", line 37, in insert_coins
    video_list = self.bilibili_http.get_video_list()
  File "/ql/data/scripts/BilibiliDailyUp/core/bilibili_http.py", line 171, in get_video_list
    query = get_query(ck=self.ck_str, mid=random_uid, ps=30, pn=1)
  File "/ql/data/scripts/BilibiliDailyUp/core/bilibili_encrypt.py", line 52, in get_query
    img_key, sub_key = get_wbi_keys(ck)
  File "/ql/data/scripts/BilibiliDailyUp/core/bilibili_encrypt.py", line 42, in get_wbi_keys
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://api.bilibili.com/x/web-interface/nav

**Comment by Wyatt1026** [comment]
拉到本地测试看看是不是你服务器网络的问题  因为我在本地测试没有问题

**Comment by ata666** [comment]
![aaa](https://github.com/Wyatt1026/BilibiliDailyUp/assets/90944267/29518a48-c40b-4f53-9e22-64f9a0915d97)
还是一样的报错

**Comment by ata666** [comment]
找到原因了，cookie最后一个分号去掉就行了，谢谢。
