### ISSUE TITLE
video_list无法获取

### ISSUE THREAD

**Issue by AdeSpike** [Wyatt1026/BilibiliDailyUp#29]
函数运行无法获取到视频列表，中断退出，疑似B站对接口进行了变动，以前的方式无法通过验证，获取的视频列表数据为空。
```shell
2024-05-14 07:42:47,412 [INFO] =========以下是任务信息=========
2024-05-14 07:42:47,524 [INFO] 登录任务未完成
2024-05-14 07:42:47,524 [INFO] 观看视频任务未完成,即将开始观看视频任务……
2024-05-14 07:42:47,921 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:48,984 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:50,047 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:51,111 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:52,169 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:53,252 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:54,315 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:55,375 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:56,432 [INFO] 获取video_list失败,延迟一秒重试
2024-05-14 07:42:57,493 [INFO] 获取video_list失败,延迟一秒重试
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    bilibili.go()
  File "/code/core/bilibili.py", line 411, in go
    self.__do_job(ck)
  File "/code/core/bilibili.py", line 308, in __do_job
    self.watch_video_task(ck)
  File "/code/core/bilibili.py", line 223, in watch_video_task
    video_list = self.__get_video_list(ck)
  File "/code/core/bilibili.py", line 122, in __get_video_list
    video_list = video_res['data']['list']['vlist']
KeyError: 'data'
````
经过调试，在运行bilibili.py中的`__get_video_list(self, ck)`函数时，拼接形成的`get_video_list_url`参数内的链接访问被B站拦截，反馈报错如下：
```shell
{
    "code": -412,
    "message": "request was banned",
    "ttl": 1
}
```
导致后续函数无法正常执行。

**Comment by Wyatt1026** [comment]
已修复 工作繁忙抱歉
