### ISSUE TITLE
好像失效了，运行报错找不到list这个键

### ISSUE THREAD

**Issue by AdeSpike** [Wyatt1026/BilibiliDailyUp#5]
Traceback (most recent call last):
  File "E:/*****/*****/bilibili/main.py", line 17, in <module>
    bilibili.go()
  File "E:\*****\*****\bilibili\bilibili.py", line 299, in go
    OOOO0O00O0O0O0O0O .__OO0O0OO0O000O0OO0 (O0O00O0O0OO00000O )#line:428
  File "E:\*****\*****\bilibili\bilibili.py", line 202, in __OO0O0OO0O000O0OO0
    OO00O00OO0O0OOO00 =O0OOO000O00O000OO .__O0OOO0O0O0O0OOOOO (O000000OO0OO0O000 )#line:319
  File "E:\*****\*****\bilibili\bilibili.py", line 91, in __O0OOO0O0O0O0OOOOO
    OO00OO0OOO0O00O00 =O0O00OO00OOOOO0OO ['data']['list']['vlist']#line:157
KeyError: 'list'

**Comment by ClydeTime** [comment]
同，显示禁止爬虫，求修复

**Comment by Wyatt1026** [comment]
修复了。官方API更新频繁 大概一两个月就更新一次
