### ISSUE TITLE
分享失败，求大佬解

### ISSUE THREAD

**Issue by lueasy559** [Wyatt1026/BilibiliDailyUp#6]
报错如下
Run python3 main.py
[17:28:07]INFO: 成功添加1个cookie,开始任务……
[17:28:07]INFO: 正在签到第1个账号……
[17:28:08]INFO: cookie有效即将开始查询任务……
[17:28:08]INFO: =========以下是任务信息=========
[17:28:09]INFO: 登录任务已完成
[17:28:09]INFO: 观看视频任务已完成
[17:28:09]INFO: 投币任务已跳过
[17:28:09]INFO: 分享任务未完成,即将开始分享任务……
Traceback (most recent call last):
  File "/home/runner/work/BilibiliDailyUp/BilibiliDailyUp/main.py", line 12, in <module>
    bilibili.go()
  File "/home/runner/work/BilibiliDailyUp/BilibiliDailyUp/core/bilibili.py", line 396, in go
    self.__do_job(ck)
  File "/home/runner/work/BilibiliDailyUp/BilibiliDailyUp/core/bilibili.py", line 33[4](https://github.com/lueasy559/BilibiliDailyUp/actions/runs/4950773223/jobs/8854829953#step:3:5), in __do_job
    self.share_video_task(ck)
  File "/home/runner/work/BilibiliDailyUp/BilibiliDailyUp/core/bilibili.py", line 28[6](https://github.com/lueasy559/BilibiliDailyUp/actions/runs/4950773223/jobs/8854829953#step:3:7), in share_video_task
    video_list = self.__get_video_list(ck)
  File "/home/runner/work/BilibiliDailyUp/BilibiliDailyUp/core/bilibili.py", line 130, in __get_video_list
    video_res = self.session.get(url=get_video_list_url, headers=headers).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4[7](https://github.com/lueasy559/BilibiliDailyUp/actions/runs/4950773223/jobs/8854829953#step:3:8) (char 46)
Error: Process completed with exit code 1.

**Comment by Wyatt1026** [comment]
问题已定位修复,是bilibili的一个API返回的数据有点问题,学业繁忙才看到,祝使用愉快
