### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by sunnyhmz7010** [Wyatt1026/BilibiliDailyUp#7]
开始运行...

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[22:49:31]INFO: 成功添加1个cookie,开始任务……
[22:49:31]INFO: 正在签到第1个账号……
[22:49:31]INFO: cookie有效即将开始查询任务……
[22:49:31]INFO: =========以下是任务信息=========
[22:49:31]INFO: 登录任务已完成
[22:49:31]INFO: 观看视频任务已完成
[22:49:31]INFO: 投币任务未完成,即将开始投币任务
[22:49:31]INFO: 投币任务未完成,即将开始投币任务
[22:49:31]INFO: 本次投币任务数量:5
Traceback (most recent call last):
  File "/workspace/BilibiliDailyUp/main.py", line 12, in <module>
    bilibili.go()
  File "/workspace/BilibiliDailyUp/core/bilibili.py", line 400, in go
    self.__do_job(ck)
  File "/workspace/BilibiliDailyUp/core/bilibili.py", line 326, in __do_job
    coin_count = self.insert_coin_task(ck, coin_num, job)
  File "/workspace/BilibiliDailyUp/core/bilibili.py", line 271, in insert_coin_task
    coin_res = self.__do_insert_coins(ck)
  File "/workspace/BilibiliDailyUp/core/bilibili.py", line 200, in __do_insert_coins
    video_list = self.__get_video_list(ck)
  File "/workspace/BilibiliDailyUp/core/bilibili.py", line 135, in __get_video_list
    video_list = video_res['data']['list']['vlist']
KeyError: 'data'

运行结束。

**Comment by Disky** [comment]
api修改了，data/api.py
get_video_list_url = 'https://api.bilibili.com/x/space/arc/search?mid={}'
修改为
get_video_list_url = 'https://api.bilibili.com/x/space/wbi/arc/search?mid={}'

**Comment by Wyatt1026** [comment]
问题已定位修复。API已经更新为新的。 但是目前好像还是有概率请求出现-403失败的情况 加了一个死循环判断。应该没啥问题了。感谢反馈
